services:

  ecommerce:
    build: ./project-ecommerce-t8-25

    ports:
      - "3000:3000"

    env_file:
      - ./project-ecommerce-t8-25/.env.docker

  file-manager:
    build: ./file-manager

    ports:
      - "4000:4000"

    env_file:
      - ./file-manager/.env.docker